### PR TITLE
FileOptimized

### PR DESCRIPTION
**Pull request by TPS**
@Ace-Dent  [As requested](https://github.com/shssoichiro/oxipng/issues/420#issuecomment-1637824591), I [FileOptimized](https://github.com/shssoichiro/oxipng/issues/326#issuecomment-711372708) everything in the repo that _might_ make sense.  Feel free to pick & choose as you see fit. 🙇🏾‍♂️

### CODE REVIEW

**Comment by ace-dent** [comment]
Thanks @TPS! I'm very grateful you spent time and energy on this... 
I'm sorry, I should have been very specific in my request:
- Most files purposefully contain metadata and have been pre-optimized sufficiently.
- The PBM files are stored in human-readable form (ASCII text), for flexibility and long term archival.
- I welcome any lossless compression of the `previews` png images, that have no metadata.

I shall add these details to `CONTRIBUTING.md` in the near future. Sorry this was not provided already.
I'd love to include your optimized file: `previews\Gingham.png`... could you provide that by itself? Or I can just commit it if easier (please let me know your GitHub-provided 'no-reply' email, to include you as a co-author).

Thanks again - I truly appreciate your interest in this project!

**Comment by TPS** [comment]
@ace-dent No worries.  As I said, choose as you like.  I'm old-school, so my commit e-mail is still `TPS@users.noreply.github.com`.

**Comment by ace-dent** [comment]
Done. :-)
Many thanks, 
Andrew

**Comment by TPS** [comment]
@ace-dent I meant to ask:  why do you keep PNG images for these?  WebP is as universal online now, & is better in just about every aspect.

**Comment by ace-dent** [comment]
@TPS - In future I will provide JXL, in addition to the legacy png format (which will still be provided for fallback). IMHO, WebP doesn't have as universal support (outside of the browser) and will be replaced by JXL in the long-term.

**Comment by TPS** [comment]
I agree, generally, but JxL's compressor is still not as mature as WebP's for edge cases like these, & has Google actively keeping it out of their codebases.  Interim, it might be worth investing in WebP, especially as it can be efficiently automated.

**Comment by ace-dent** [comment]
@TPS - Thanks for the suggestion and input. I quickly did a trial with one preview image:

111 Bytes - png
 78 Bytes - WebP
 74 Bytes - JXL
 64 Bytes - WebPv2

(Using `cjxl -e 10 -d 0 --patches=0 <INPUT> <OUTPUT> --allow_expert_options`)

Ultimately I may have previews inlined with the html, as base64 images. Every 3 bytes converts to 4 base64 characters, so:
148 chrs - png
104 chrs - WebP
100 chrs - JXL 
 88 chrs - WebPv2

PNG > JXL saves 48 base64 characters.
JXL > WebPv2 saves 12 base64 characters.

I will keep monitoring the adoption of WebPv2 and JXL, and also hope JXL continues to improve compression ratios for pixel art.

**Comment by TPS** [comment]
For WebPv2, how are you accessing it?

**Comment by ace-dent** [comment]
Quickly tested with [sqoosh.app](https://squoosh.app/).
See also https://github.com/GoogleChromeLabs/squoosh

**Comment by TPS** [comment]
WebPv2 doesn't seem to have "official" binary releases; I'm surprised if it were to have browser support.

What are the format specifications you'd settle on for this image repo?  The absolute smallest representation per _each_ file?  Smallest overall format?  (Eventual supposed) browser support?  I'm sure there're tons of arcane formats to be tried, depending on what you're aiming for.

**Comment by ace-dent** [comment]
> What are the format specifications you'd settle on for this image repo?

Images will always be available as png; so that is the primary target for optimization efforts. In addition, one other format will be chosen for encoding as base64. I'd prefer JXL but it's open to discussion. Browser support is key.

> Smallest overall format?

Yes. All `preview` images should be of the same format.

>  I'm sure there're tons of arcane formats to be tried

Yes. Old formats like GIF and v1.0 BMP have small headers, which may help... but I'm only looking at current technology which is likely to be useful and commonplace. 

I'm fairly confident there are some missed opportunities with the png encoder, so I think it's a nice edge case to test with. :-)

**Comment by TPS** [comment]
> I'm fairly confident there are some missed opportunities with the png encoder, so I think it's a nice edge case to test with. :-)

If so, brute exhaustive search &/or PRs to implement those opportunities would likely be the way to go.  FileOptimizer's express purpose is to meet/beat lvl 9 compressions, & it (evidentally) found just that 1.  What you're looking for is, effectively, tuned lvl 10 searches, like you did for `WebP`[`2`]/`JxL`.

**Comment by TPS** [comment]
> Old formats like GIF and v1.0 BMP have small headers

`GIF` _is_ universal.  Run tests like above?  I think proved-optimal compression exists at such small sizes.

**Comment by TPS** [comment]
@ace-dent I'm thinking of running a project that'll probably turn into a PR, based on our above conversation.  Would you mind directing me to the canonical _source_ files that you'd most like to see optimally compressed versions of?

**Comment by ace-dent** [comment]
@TPS - Sounds intriguing! Currently pattern `previews`[here](https://github.com/ace-dent/8x8.me/tree/main/previews) as highly optimized `png` (or `jxl`) files.

**Pull request closed without merging**
